language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
services:
  - docker
install:
  - pip install virtualenv --upgrade
  - make install
  - make test-install
script:
  - make test
deploy:
  provider: script
  script: make docker-build && make docker-push
  skip_cleanup: true
  on:
    tags: true
    python: "3.6"
